---
coverage:
  status:
    project:
      default:
        target: auto
      python:
        target: auto
        paths:
          - bumper/*
    patch:
      default:
        target: auto
      python:
        target: auto
        paths:
          - bumper/*
