---
name: Report an issue
description: Report an issue
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Please remember: This issue form is for reporting *bugs* only!

        If you have a feature request or a question, please use discussions.
  - type: checkboxes
    attributes:
      label: Checks
      options:
        - label: I have searched the existing issues and no issue is describing my issue
          required: true
        - label: I have installed the latest version
          required: true
        - label: I have provided clear steps to reproduce the issue
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here to communicate to the
        maintainers. Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.

  - type: markdown
    attributes:
      value: |
        ## Environment Details
        Note: This project runs by default inside Docker. Please provide details about your Docker setup.

  - type: input
    id: docker_version
    validations:
      required: true
    attributes:
      label: Docker Version
      placeholder: e.g., 20.10.7

  - type: input
    id: host_os
    validations:
      required: true
    attributes:
      label: Host Operating System
      placeholder: e.g., Ubuntu 20.04

  - type: input
    id: device
    validations:
      required: true
    attributes:
      label: On which deebot vacuum you have the issue?
      placeholder: Deebot Ozmo 950
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: Which version of bumper are you using?
      placeholder: X.X.X
  - type: checkboxes
    id: related_to
    attributes:
      label: Is the bug related to any of the following?
      options:
        - label: MQTT
        - label: XAMPP
        - label: Web Server
  - type: markdown
    attributes:
      value: |
        # Configuration

  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: >
        For example, error message, or stack traces.
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
        Please note, you can attach screenshots or screen recordings here, by
        dragging and dropping files in the field below.
